### ISSUE TITLE
-performance

### ISSUE THREAD

**Issue by Yjjx** [Yjjx/performance#1]
performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance-performance

**Comment by ANDRoid7890** [comment]
you forgot to add one `-performance` in the end
